name: drl-jumping
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9.7
  - gym=0.21.0
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - numpy=1.21.5
  - scipy=1.7.3
  - pip
  - pip:
    - pygame==2.1.2
